### ISSUE TITLE
Hide Login

### ISSUE THREAD

**Issue by supergibbs** [morincer/teamcity-plugin-saml#1]
First of all, thank you for creating this! It's long overdue and something Jetbrains should have included. Your plugin works great!

Is there a way to hide the user/password boxes so only the Sign in with SSO button is available? Not a big deal but would be nice.

**Comment by morincer** [comment]
Hi Jesse,

I really glad the plugin is helpful for you. To be honest, I don't know if
hiding login/password is possible - the "Login with SSO" button is plugged
into the login page and doesn't have control over the rest of it. However,
I'll check the possibility and, if it is possible, will include the feature
into the next release.

ср, 14 авг. 2019 г. в 20:54, Jesse Mandel <notifications@github.com>:

**Comment by supergibbs** [comment]
I was looking around and found another implementation that does it:

https://github.com/szemek/teamcity-saml/blob/master/src/main/resources/buildServerResources/saml.jsp#L7-L13

I like your UI for configuring better though.
