### ISSUE TITLE
If users have not logged in, they don't receive notification emails

### ISSUE THREAD

**Issue by TI-asilva** [morincer/teamcity-plugin-saml#121]
Not sure if this is a dupe of [#64](https://github.com/morincer/teamcity-plugin-saml/issues/64), but users do not get created until they log in. This makes sense in the context of how SAML works, but it means that if a user that has not logged in commits a build breaking change, they will not get an email notification because their user account has not been created and thus their email address is unknown.

Would it be possible to sync AD groups of users so that we have their username/email ahead of time so that it can be used for sending build notification emails?

**Comment by morincer** [comment]
Hi Anthony, 
I don't really think this is a valid use case for the plugin - it doesn't do any accounts synchronization nor interacts with any external LDAP catalogues in any manner - this is exactly opposite to how SAML/SSO works. However, I'm pretty sure you can do AD synchronization using other plugins and then use SSO to login
