### ISSUE TITLE
New minor release to include latest fixes

### ISSUE THREAD

**Issue by anghelcovici** [morincer/teamcity-plugin-saml#122]
Hello,

Love the plugin, very useful. It's a very minor nit, but the redirect bug that was "recently" fixed is very exciting news.
@morincer - any chance you can trigger a new release? Some folks might not want to update unless there is an "official" release.

**Comment by morincer** [comment]
hi @anghelcovici , I'm bit busy at the moment, but I'll do my best to make a release this weekend
