### ISSUE TITLE
404 error on redirection to Okta

### ISSUE THREAD

**Issue by RL57a** [morincer/teamcity-plugin-saml#17]
Hi,

We are using TeamCity Version 2019.1.2 (build 66342) and have successfully installed and set-up the SAML plugin: snapshot-20190902062401

We can successfully login to TeamCity via Okta's applcation page, however when we click on the "Login with Okta SSO (App Required) button on the TeamCity landing page, we are redirected, but get a 404 error.

We've checked and double checked the Single Sign-On URL settings in the SAML Plugin in TeamCity and everything looks good.

The Single Sign-On URL is basically set-up as: https://ouroktadomain.okta.com/app/ourdomain_teamcity_1/abc123/sso/saml

However, if we click on the SSO button on the TeamCity page we get redirected to: 
https://ourteamcityurl.com/app/ourdomain_teamcity_1/abc123/sso/saml

...So, for some reason the actual redirected URL is a mixture of the Okta SSO URL and the teamCity URL.

NOTES:
1. We did notice that the "Single Sign-On URL" option appears twice in the SAML config in TeamCity. I imagine that the second appearance should actually be the SSO Sign-OUT URL?

2. If we copy and paste the correct Single Sign-On URL (https://ouroktadomain.okta.com/app/ourdomain_teamcity_1/abc123) into a new browser window then we are successfully redirected and authenticated with Okta, and in-turn we are re-directed back to TeamCity and logged in with no issues. 

Please see attached image.

Many thanks!

<img width="724" alt="SAML" src="https://user-images.githubusercontent.com/57257542/68024669-ae426880-fca2-11e9-9baf-70f6bb527c95.png">

**Comment by morincer** [comment]
Hi! I'll check this.
Quick question - did you use "Import Metadata" function or specified the values directly?

**Comment by RL57a** [comment]
> Hi! I'll check this.
> Quick question - did you use "Import Metadata" function or specified the values directly?

Hi, 

Wow! Thanks for the super quick reply. We've tried both with and without the Import Metadata function.

Wondering if we can disable and re-enable the plugin and see if this helps??
Thanks, again!

**Comment by morincer** [comment]
I've checked with the latest version and wasn't able to spot any issue - it redirects correctly. My best guess is that you have something in your URL that makes it inproperly handled. Could you give me the actual URLs of your teamcity installation and okta? 

If it is not to be disclosed you may replace your company name with something random - just keep the rest of the URL intact. 

Also, what happens if you specify, say, google.com as the SSO endpoint? Is it still interfering with your teamcity's domain name?

**Comment by RL57a** [comment]
Hi, 

The IdP Single Sign-on URL is: [https://rufusleonard.okta.com/app/rufusleonardltd_teamcity_1/exkc6pc1ry3RZ2RvI1t7/sso/saml](url)

The Entity  ID (Audience) is: [https://teamcity.ci.rufusleonard.com/app/saml/callback/ ](url)

The SP Single Sign-On URL (Recipient) is : [https://teamcity.ci.rufusleonard.com/app/saml/callback/ ](url)

We changed the IdP Single Sign-on URL to: [https://whatever.okta.com/app/rufusleonardltd_teamcity_1/exkc6pc1ry3RZ2RvI1t7/sso/saml](url) but it made no difference

Thanks

**Comment by morincer** [comment]
Well, I checked with your particular URL and do not see any issue - it shows me the okta login page. 
Is it possible that something (like proxy) is interfering into the process?
Let's try the following:
1. Make sure you're logged off from Okta
2. Specify the parameters using the "Import Metadata" feature - just to be sure. Don't forget to save.
3. If it's possible - check the config file at <TEAMCITY DATA DIR>/config/saml-plugin.config.json so it contains valid values. 
4. Make sure you have a correct server address specified for Teamcity (well, you should - but who knows)
4. Try to login

**Comment by RL57a** [comment]
Apologies, but this is not my environment (I'm helping our Dev guys) and it turns out that the TeamCity webapp IS PROXIED. 

I confirmed this by running a SAML trace, and saw the 404 was being returned from the Proxy. 

Apologies for the confusion.

**Comment by morincer** [comment]
Closing the issue then.
