### ISSUE TITLE
Add support for standard SAML Redirect/POST flow

### ISSUE THREAD

**Issue by morincer** [morincer/teamcity-plugin-saml#20]
Currently plugin supports only IdP initiated logins - need to add SAML Redirect and POST flow

**Comment by graynes** [comment]
Does this mean that when we log into Teamcity via SAML it won't redirect us to IdP (Okta)?

**Comment by morincer** [comment]
No, it redirects to Okta as Okta uses IdP-initiated flow by default and
provides URL for each of the SPs (in fact, the plugin has been originally
tested with Okta, no issues there).

The thing is that the IdP should have a particular URL set up for each SP
and know how to handle the rest of communications.
The Redirect/POST flow assumes that SP first sends SAMLRequest to general
IdP URL, and that request contains information necessary to handle the
authentication. That kind of flow is not currently supported.


пт, 17 янв. 2020 г. в 14:43, graynes <notifications@github.com>:

**Comment by davidsielert** [comment]
I have a mock of this almost working but I cannot seem to get it to load(initialize) opensaml within teamcity

**Comment by morincer** [comment]
Ok, I'll take a look this week, probably it won't be too hard to implement.

**Comment by davidsielert** [comment]
I got it working finally I can submit a PR once I finalize this code

**Comment by morincer** [comment]
Added SAMLRequest to initial handshake so now should work fine
