### ISSUE TITLE
ADFS is not working

### ISSUE THREAD

**Issue by dimagohere** [morincer/teamcity-plugin-saml#23]
Hello there!

are you guys still working on it? I tried to setup this with my ADFS but it did not work. I got this error:

![tc-2](https://user-images.githubusercontent.com/62297487/76870286-e3111f80-683f-11ea-936f-4cccef24b915.PNG)
![tc-](https://user-images.githubusercontent.com/62297487/76870348-f8864980-683f-11ea-995b-41514dd6f9f6.PNG)

**Comment by morincer** [comment]
Hi Diego, 
Yes, I'm working on it, but not that active as I used to be. I saw your e-mail and will take a look on the issue.

**Comment by morincer** [comment]
Would you please give a try to the new version and check if it works? If not - I'll need teamcity log to troubleshoot the issue.
