### ISSUE TITLE
Error with Azure AD

### ISSUE THREAD

**Issue by Amousy** [morincer/teamcity-plugin-saml#24]
Hello,

I have the following error just after clicking on the SSO login button.
Error message: SAMLRequest or SAMLResponse must be present as query string parameters in HTTP request for SAML Redirect binding.

Thanks
Amousy

**Comment by morincer** [comment]
Mostly likely you're using SAML Redirect/POST flow which is not currently supported. Check #20 
Please confirm that you are using IdP-initiated procedure

**Comment by Amousy** [comment]
I use well the IdP-initiated configuration but if the plugin not uses HTTP redirect binding when sending the SAML request this can't work with Azure AD.

https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-problem-federated-sso-gallery#saml-request-not-present-in-the-request 

Do you plan to implement this feature soon? I tried to use the David Sielert version without success.

**Comment by morincer** [comment]
Yes, this feature is in the nearest roadmap. Stay tuned.

**Comment by morincer** [comment]
You may give a try to the new version - now IdP-initiated login flow is supported. I don't have AD sandbox so was not able to test with that provider but it seems to work fine with Keycloak. Feel free to contact me if you have any issues.

https://github.com/morincer/teamcity-plugin-saml/releases/tag/v1.1
