### ISSUE TITLE
Change package UrlValidator

### ISSUE THREAD

**Issue by dmitriy-kharchenko** [morincer/teamcity-plugin-saml#25]
Good day!

Need to change UrlValidator package from `org.apache.commons.validator.UrlValidator` to `org.apache.commons.validator.routines.UrlValidator` bacause old package don't validate URL of type `http://do-openam.localnet.local:8080/openam/`

[Similar issue on StackOverflow](https://stackoverflow.com/questions/13288847/why-urlvalidator-do-not-work-for-some-of-my-urls)

**Comment by morincer** [comment]
Reference is missing. Let me fix it

**Comment by dmitriy-kharchenko** [comment]
I'm sorry, hastened. When could we meet a new release?

**Comment by morincer** [comment]
I'm generation minor release right now - it will contain only security updates and your fix so you may grab it as it finishes. In parallel I'm testing AuthnRequest functionality which will probably allow using AD-based IdP - that would come until end of week.
