### ISSUE TITLE
SAML request contains the wrong URL in AssertionConsumerServiceURL param

### ISSUE THREAD

**Issue by dmitriy-kharchenko** [morincer/teamcity-plugin-saml#29]
When TeamCity is located behind HTTPS reverse proxy its SAML request can contain the wrong URL in `AssertionConsumerServiceURL` param.

For example: `http://teamcity.localnet.local/app/saml/callback/` instead of `https://teamcity.localnet.local/app/saml/callback/`

Parameter `Server URL` in `Global settings` is configured right.

**Comment by morincer** [comment]
Fixed and released. Check v1.1.1

**Comment by dmitriy-kharchenko** [comment]
Thanks!)
