### ISSUE TITLE
Single Sign-On URL over https

### ISSUE THREAD

**Issue by supergibbs** [morincer/teamcity-plugin-saml#3]
It works fine but in the `SAML Settings` the `Single Sign-On URL` is hard coded to use http. My teamcity server uses https so if it is possible to detect that and show correctly, that would be great.

Also there is a typo in the label `Recepient` -> `Recipient` :)

**Comment by morincer** [comment]
Now the callback URL is generated basing on the server URL configured for the Teamcity
