### ISSUE TITLE
Reply URL in the request does not match

### ISSUE THREAD

**Issue by Amousy** [morincer/teamcity-plugin-saml#30]
Hi morincer,

thanks for your new version! It's very helpfull :)

I've got one more mistake with Azure AD:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application.

I did put the url https://myserver/app/saml/callback/ in the Azure AD configuration as indicated in the TeamCity settings.
However, in the SAML query it's the url below which is put and which explodes the mismatch.
http://myserver:443/app/saml/callback/

Can you check?

Thanks
amousy

**Comment by morincer** [comment]
Hi @Amousy, did you use the version 1.1.1 to test? It now takes the root url value from the server configuration, so it shouldn't clash with your setup. 
If yes - would you please send me the saml query sent to ADFS and screenshot of the global teamcity configuration (I need the server URL) along with screenshot of the SAML settings page?

Note: you may blur the sensitive data like certificate, just keep URLs

**Comment by Amousy** [comment]
Sorry, my bad. I was still on version 1.1. You're going too fast :D 

btw, a small suggestion, the error message when the email is not found (with the user creation option set to Off) is a bit too technical for an end user:
"SAML request NOT authenticated for user id xxx: user with such username or plugin:auth:HTTP:teamcity-saml-id property value not found"

**Comment by morincer** [comment]
Well, when I was creating the first version of the plugin, the end-users were not my biggest concern :) Anyway, good suggestion, created FR for that #31
