### ISSUE TITLE
disabled login screen under local admin teamcity account now can't get login screen back

### ISSUE THREAD

**Issue by mkaithakottil** [morincer/teamcity-plugin-saml#33]
disabled login screen under local admin teamcity account now can't get login screen back.  I did not setup other users with admin priviliges in teamcity yet...so now i can't log in with the local admin account.  is the only resolution to delete the plugin from the teamcity server and start over?

**Comment by mkaithakottil** [comment]
just uninstalled plugin and readded the plugin and was able to get option back to show login screen fields.

**Comment by morincer** [comment]
Well, in fact you had two simpler options :)
Option 1 - adjust plugin settings manually - the settings file is located at config/saml-plugin.config.json - just change the hideLoginForm value to False.

Option 2 - the plugin hides the login button by just adding style to the page: 
<style>
        .loginForm {
            display: none;
        }
</style>
So you can open developer tools in browser (F12) locate that node in the DOM tree and just delete it (or change the style to whatever you need).
