### ISSUE TITLE
Fatal error after server restart

### ISSUE THREAD

**Issue by snweiss** [morincer/teamcity-plugin-saml#34]
I've installed the plugin on a test environment and managed to make the plugin work. however, it seems that it's causing some issues during server startup and makes it unusable. After the "Initializing TeamCity" phase, I get errors indicating `java.lang.NoClassDefFoundError: Could not initialize class` or `javax.xml.stream.FactoryConfigurationError: Provider for class ... cannot be created` with a different classes. I've attached a server.log from one server instance where multiple of these error occurred. it seems that every time I access the login page it generate a slightly different error. 

I tried to debug this a bit and found that the class for SamlLogin.jsp (i.e. SamlLogin_jsp.class) doesn't get auto generated for some reason.
When I removed the plugin's zip file from the `%ProgramData%\JetBrain\TeamCity\plugins` folder I was able to start the server. when I copy back the zip file to place, sometimes it starts, but most of the times it doesn't.

I initially encountered the problem on TeamCity 2019.1.5, but the issue also reproduced on 2019.2.2.
[server.log](https://github.com/morincer/teamcity-plugin-saml/files/4415478/server.log)

**Comment by morincer** [comment]
Hi!
To be honest, I didn't test the plugin on version 2019 - probably, some
Java versions mismatch. I'll check and get back to you.

ср, 1 апр. 2020 г. в 16:43, snweiss <notifications@github.com>:

**Comment by snweiss** [comment]
Wow that was super fast, thanks!
If there's any more info you need - just let me know.

**Comment by morincer** [comment]
Tested on 2019 with my local setup and see no issues. If the issue still persist - please re-open the ticked
