### ISSUE TITLE
License

### ISSUE THREAD

**Issue by matbos** [morincer/teamcity-plugin-saml#36]
Hey,

I have noticed that your project has no license. I am now looking into possible solutions for our company to use and support. Lack of a license will get me blocked on the legal department.
I imagine this is a problem for other possible users as well.
Can you decide on a license and publish it?

**Comment by morincer** [comment]
Hi, it's published on Jetbrains central under MIT license. 
https://plugins.jetbrains.com/plugin/12588-saml-authentication.

Added the same to repository.
