### ISSUE TITLE
Set login button text

### ISSUE THREAD

**Issue by supergibbs** [morincer/teamcity-plugin-saml#4]
Feature request to set the text of the "Login with SSO" button. I'd like to set it to "Login with Okta" which is more familiar with my users than SSO.

**Comment by morincer** [comment]
Implemented in the vue-ui branch now. Will merge once I finish Vue transition.

**Comment by morincer** [comment]
Merged.

8bc186188427e2cdd3be724dbe16b7d4c59c97db
