### ISSUE TITLE
Allow pulling in Okta group info and map to teamcity group

### ISSUE THREAD

**Issue by prakhar05** [morincer/teamcity-plugin-saml#42]
Hello,

Is there a way to pull in group information from okta and map it to teamcity groups? If not, can this be filed as an enhancement request?

**Comment by morincer** [comment]
Do you mean changing groups in Teamcity to match those in Okta? It is not currently implemented but I will think on possible implementation. Do you have any particular usage scenario in mind?

**Comment by fatmcgav** [comment]
So just to tag onto this issue, we're currently starting a project to implement a TeamCity CI service, and one of the requirements is to restrict certain projects to certain groups.

We would like to map those groups based on Okta group membership, as that's our source of truth.

**Comment by fatmcgav** [comment]
FYI, I've opened a draft PR in #52 which adds support for mapping Okta groups to TC groups.

There's still some work to do around UI etc, but the core functionality passes the tests.
