### ISSUE TITLE
Make the plugin work with new CSRF token

### ISSUE THREAD

**Issue by morincer** [morincer/teamcity-plugin-saml#45]
Created from #39 . Make the plugin work with new CSRF protection mechanism

**Comment by morincer** [comment]
Finalized the implementation - added CORS filter exception for SAML login endpoint. If the filter exception is enabled (by default) SAML assertion sent to the callback URL are considered CORS-safe.

**Comment by slatted** [comment]
FYI, this was a great update and truely appreciated!  Thanks very much

**Comment by morincer** [comment]
Thanks, I'm really glad my pet-project helps people :)
