### ISSUE TITLE
Log out and immediate log in fails when using Okta

### ISSUE THREAD

**Issue by joe-hutchinson-cko** [morincer/teamcity-plugin-saml#60]
Receiving the following error when trying to log in after logging out. 

![image](https://user-images.githubusercontent.com/46525238/99274491-4f567f80-2822-11eb-8be7-4e78ec6b6aca.png)

I'm using TeamCity 2020.1.5 with Okta.

**Steps to reproduce:**

1. log in using SSO either via Okta or by the SSO button on TeamCity log in page
1. log out
1. log in using SSO either via Okta or by the SSO button on the TeamCity log in page
1. Log in fails and you should see the error above
1. Wait for a few minutes
1. Log in using SSO either via Okta or by the SSO button on the TeamCity log in page
1. Log in succeeds

Its strange the issue appears to resolve itself after a period of time. Have you run into this issue before? So far I've tried setting `teamcity.csrf.paranoid=false` but it didn't seem to make any difference.

**Comment by morincer** [comment]
Hi Joe,

Are you able to collect logs as specified at https://github.com/morincer/teamcity-plugin-saml#additional-logging and attach them here?

**Comment by joe-hutchinson-cko** [comment]
Hey,
Sure thing I've this log shows the failed SSO request. 
[teamcity-auth.log](https://github.com/morincer/teamcity-plugin-saml/files/5548520/teamcity-auth.log)

**Comment by joe-hutchinson-cko** [comment]
@morincer any ideas what could be causing this behavior?

**Comment by morincer** [comment]
Checking. Very strange behavior, probably something going wrong with
session invalidation.

ср, 18 нояб. 2020 г. в 12:21, Joe <notifications@github.com>:

**Comment by morincer** [comment]
Hi Joe, I was testing with different versions of Teamcity (and Okta provider) - and I didn't spot any issues. 
Do you have something in the middle like proxy or load balancer which might cache requests? 
If not - would you please collect log of full sequence (log in, log out, login again).

**Comment by joe-hutchinson-cko** [comment]
Hey, yes I have an AWS ALB in front of this service. Could that be caching requests?

**Comment by joe-hutchinson-cko** [comment]
Found the issue, [step 5](https://github.com/morincer/teamcity-plugin-saml/blob/master/docs/OktaSetup.md) says use the value returned in the 403 message, for me however it should be the address of Okta. Once set I can repeatedly log in and out without issue. Thank you for your help diagnosing this problem.

**Comment by morincer** [comment]
It might be an issue with load balancer - but anyway, glad you have it sorted :)
