### ISSUE TITLE
AWS SSO not logging in directly

### ISSUE THREAD

**Issue by Gman54** [morincer/teamcity-plugin-saml#61]
We are using TeamCity Enterprise 2020.1 (build 78475) when clicking on the AWS SSO file for TeamCity we go directly to the TeamCity login page, it does not sign us in directly . The SSO login button will work and allows us to login.

What we really need it to log us in directly.

**Comment by morincer** [comment]
Hi @Gman54 

https://github.com/morincer/teamcity-plugin-saml#troubleshooting

Any additional info like logs, screenshots etc. are appreciated.

**Comment by Gman54** [comment]
Thanks for the quick reply. Here is what I have.
![image](https://user-images.githubusercontent.com/53305846/102666520-2e50b980-4155-11eb-85eb-76def436f3c2.png)

[debug-auth1.txt](https://github.com/morincer/teamcity-plugin-saml/files/5718336/debug-auth1.txt)
![image](https://user-images.githubusercontent.com/53305846/102666645-78399f80-4155-11eb-8a88-bfffbd054418.png)

Hope it helps.

**Comment by morincer** [comment]
/app/saml/callback is the URL where SP should POST the SAML messages, it is not the page which initiates login. To initiate login you should use /app/saml/login/ (this is where you're in fact going to when clicking "Login with SSO" button).

I don't know hovewer if AWS allows specifiying different URLs for these different cases, but if it does - give it a try.

**Comment by morincer** [comment]
Closed due to no response.

**Comment by Gman54** [comment]
Sorry, it took a while to implement, but changing the URL worked, thank you!
