### ISSUE TITLE
Support authenticating on Secondary servers

### ISSUE THREAD

**Issue by fatmcgav** [morincer/teamcity-plugin-saml#62]
So I'm not sure if this is a change required to this plugin, TeamCity, or both.

However currently it appears that this plugin does not run on Seconday servers.
This makes it impossible to login to a secondary server using SAML authentication.

A couple of links of note:
- https://www.jetbrains.com/help/teamcity/configuring-secondary-node.html#Using+Plugins
- https://plugins.jetbrains.com/docs/teamcity/plugin-development-faq.html#How+to+adapt+plugin+for+secondary+node
- https://youtrack.jetbrains.com/issue/TW-58322

**Comment by morincer** [comment]
@fatmcgav , thanks for reporting - I had no idea about the secondary nodes in TC :) 
I'll take a look on them first week of Jan and get back with results.

**Comment by fatmcgav** [comment]
@morincer no worries.

From a quick read of the docs above, it _might_ be as simple as just adding the additional attribute to the `teamcity-plugin.xml`... Or it might require some code changes to use `jetbrains.buildServer.serverSide.IOGuard`...

**Comment by morincer** [comment]
Well, it wasn't just that :) 
Add support for secondary nodes, did some basic testing. There are few limitations though - added [section](https://github.com/morincer/teamcity-plugin-saml#secondary-node-authentication-support) into Readme

**Comment by fatmcgav** [comment]
Awesome, thanks for the quick turnaround there @morincer .

Will give the new release a test...
