### ISSUE TITLE
question - is the group mapping only supported for Okta SSO integration? or any Custom SSO

### ISSUE THREAD

**Issue by jastsai** [morincer/teamcity-plugin-saml#71]
I am using AWS SSO with this plugin to enable the TeamCity SAML SSO integration and I am wondering if the group mapping is only supported for Okta SSO integration?

I created group in AWS SSO with the same name as I have in one of the teamcity group and seems the group mapping isn't working.

Update:
- I inspected the saml response and looks like it returns the group id from AWS SSO. The mapping that I configured is as memberOf  --> ${user:groups}
I wonder how I can return group name instead of group id in my configuration?

Thanks

**Comment by morincer** [comment]
hi @jastsai , sorry I don't get the question. The group mapping is universal (not bound to particular IdP) and, unfortunatelly, I don't know if it's possible to change the way AWS SSO sends groups in SAML response - you better refer to AWS SSO documentation/support. If you give me an example of groups returned from AWS SSO and expected mapping I would think about probable solutions.
