### ISSUE TITLE
Update not recognized

### ISSUE THREAD

**Issue by Amousy** [morincer/teamcity-plugin-saml#72]
Hello,

The 2021 version is not well recognized in the teamcity interface. 
It proposes to go back to the 2020 version after a manual installation.

![teamcity plugin settings](https://user-images.githubusercontent.com/5183126/114712692-ab212800-9d30-11eb-9aaa-604918c7288a.JPG)

Thanks!

**Comment by morincer** [comment]
Which TC version do you use?

**Comment by Amousy** [comment]
I noticed it since 2020.1.5
Now we are using 2020.2.3

**Comment by Amousy** [comment]
Hi @morincer,

Any news about this bug? 
I have just updated to TeamCity 2021.1.2 Build 92869 and I see that the error is still there.

Thanks

**Comment by morincer** [comment]
hi @Amousy , sorry for late response - I was on vacation :) 
I wasn't able to reproduce the issue so far - will continue investigation and provide some feedback.

**Comment by morincer** [comment]
Seems that build number messes Teamcity update routine. Just pushed a new release with more straightforward versioning.

**Comment by Amousy** [comment]
Hi @morincer,
Amazing! It works!
![image](https://user-images.githubusercontent.com/5183126/134130682-ba804f73-2416-4198-abb5-a80592495015.png)

Thanks!
