### ISSUE TITLE
Teamcity view wrong version after latest version

### ISSUE THREAD

**Issue by Mortagne** [morincer/teamcity-plugin-saml#84]
I installed latest version of the plugin manually on my server.

When i check if i have an update, i see this message :
![image](https://user-images.githubusercontent.com/3946452/132787455-d9d2c134-aba4-4111-8794-9a29b7e796ea.png)

**Comment by morincer** [comment]
Seems that build number messes Teamcity update routine. Just pushed a new release with more straightforward versioning.
