### ISSUE TITLE
Map full name from Google Workspace

### ISSUE THREAD

**Issue by inkdude** [morincer/teamcity-plugin-saml#90]
Hello! 
Can you add function which is map first name and last name from Google Workspace separately, because i can't create a new attribute which contains first and last name in one attribute
![image](https://user-images.githubusercontent.com/17637953/148779210-af6817e4-cfc9-4e18-b8c6-5a08ed15ce73.png)
![image](https://user-images.githubusercontent.com/17637953/148779629-ce2f3367-8a00-4dcb-b4ed-927ffac8d8e3.png)
Or maybe along with "Custom attribute" i can add something like "First+Last" which is means concatenating both attributes in one string

**Comment by morincer** [comment]
Hi @inkdude, usually such kind of transformation is supposed to be performed on IdP side - not a consumer. However, I'll evaluate implementation options for this request.

**Comment by morincer** [comment]
Implemented a custom expressions feature - check Readme.md for a syntax examples.
You may give it a try after a new version (1.4.2) is released - planning to do it today or tomorrow.
